'use client'
import {Quicksand} from "next/font/google";
import './styles/index.scss'
import {classNames} from "@/app/lib/classNames/classNames";
import {Header} from "@/app/components/Header/Header";
import Container from "@/app/components/Container/Container";
import React, {ReactNode} from "react";

const quicksand = Quicksand({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
      children: ReactNode;
}>) {


    return (
        <html lang="ru">
            <body className={classNames(quicksand.className, {}, ['app'])}>
                <Header />
                <Container>
                    {children}
                </Container>
            </body>
        </html>
    );
}
