'use client'
import {Inter} from "next/font/google";
import './styles/index.scss'
import {classNames} from "@/app/lib/classNames/classNames";
import {Theme, ThemeProvider, useTheme} from "@/app/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const theme = Theme.ORANGE;

    return (
        <html lang="ru">
            <ThemeProvider>
                <body className={classNames(inter.className, {}, ['app', theme])}>
                    {children}
                </body>
            </ThemeProvider>
        </html>
    );
}
